# Usarei uma imagem base com Python
FROM python:3.9-slim

# Definirei o diretório de trabalho dentro do container
WORKDIR /app

# Copiarei o script Python do meu computador para o container
COPY carguru.py .

# Comandos para execução do script
CMD ["python", "carguru.py"]
